### PR TITLE
Fix error output when specified unknown log level

### PR DESCRIPTION
**Pull request by ursfassler**
Problem with version 3.10.0, the code on the latest branch looks the same.

I tested changed code separately but wasn't able to build the whole app/docker image, hence not tested in this environment.

### CODE REVIEW

**Comment by lucas-akira** [comment]
Hi @ursfassler ,

Sorry for the delay in responding. As we're currently prioritizing all tasks that need to be done at the end of the quarter, we may take a bit longer to look at your PR. Rest assured we'll take a closer look at it soon.

From a quick glance the PR does indeed fix an incorrectly formatted print command we didn't notice.

In the meantime, can you signoff your commit with `git commit -s`?

**Comment by ursfassler** [comment]
@lucas-akira I know the problem now, so no pressure from my side.

I signed off my commit. Hope that is all that is needed and that I didn't missed a contribution documentation.

**Comment by lucas-akira** [comment]
Great, thanks! And no need to worry about the contribution documents, as there isn't one at the moment.

In fact, one of the tasks we're currently finishing right now is an actual contributor guideline document, along with a rewrite of the Readme page.

**Comment by lucas-akira** [comment]
Hi @ursfassler ,

We took a look at the PR, and it looks simple enough. No problems with it on our side. Can you rebase your branch to be up-to-date with `bullseye`? We can merge after that.

**Comment by ursfassler** [comment]
@lucas-akira cool! PR is rebased.

**Comment by lucas-akira** [comment]
PR has been merged. Thank you for your contribution!

**Pull request merged**
